#!/usr/bin/env bash

curDir=$PWD

if [ "$(uname)" == "Darwin" ]; then
    # Mac OS X platform
    envokeLoc=$(realpath -e /usr/local/bin/envoke)
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    # GNU/Linux platform
    # use readlink
    envokeLoc=$(readlink -f /usr/local/bin/envoke)
fi

compilerDir=$(dirname $envokeLoc)
$compilerDir/_build/install/default/bin/./evo "$@"